In [1]:
import numpy as np
import math
A = np.array([[4,3,0,0],[3,3.333,-1.667,0],[0,-1.667,-1.32,-0.907], [0,0,-0.907,1.987]])
#A = np.array([[1,1,0,0],[1,2,2,0],[0,2,3,3],[0,0,3,4]])
n = A.shape[0]
A

array([[ 4.   ,  3.   ,  0.   ,  0.   ],
       [ 3.   ,  3.333, -1.667,  0.   ],
       [ 0.   , -1.667, -1.32 , -0.907],
       [ 0.   ,  0.   , -0.907,  1.987]])

In [26]:
#test using A[0][0] to eliminate A[1][0]
r = math.sqrt(A[0][0]**2 + A[1][0]**2)
cos = A[0][0] / r
sin = A[1][0] / r

G = np.eye(n)
G[0][0] = cos 
G[0][1] = sin 
G[1][0] = -1 * sin 
G[1][1] = cos
G

array([[ 0.8,  0.6,  0. ,  0. ],
       [-0.6,  0.8,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [27]:
A1 = G @ A
np.round(A1,3)

array([[ 5.   ,  4.4  , -1.   ,  0.   ],
       [ 0.   ,  0.866, -1.334,  0.   ],
       [ 0.   , -1.667, -1.32 , -0.907],
       [ 0.   ,  0.   , -0.907,  1.987]])

In [28]:
#use A[1][1] to eliminate A[2][1]
r = math.sqrt(A1[1][1]**2 + A1[2][1]**2)
cos = A1[1][1] / r
sin = A1[2][1] / r
G = np.eye(n)
G[1][1] = cos 
G[1][2] = sin 
G[2][1] = -1 * sin 
G[2][2] = cos
G

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.46116837, -0.88731265,  0.        ],
       [ 0.        ,  0.88731265,  0.46116837,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [30]:
A2 = G@A1
np.round(A2, 3)

array([[ 5.   ,  4.4  , -1.   ,  0.   ],
       [ 0.   ,  1.879,  0.556,  0.805],
       [ 0.   ,  0.   , -1.792, -0.418],
       [ 0.   ,  0.   , -0.907,  1.987]])

In [49]:
A = np.array([[4,3,0,0],[3,3.333,-1.667,0],[0,-1.667,-1.32,-0.907], [0,0,-0.907,1.987]])
n = A.shape[0]

A_param = A.copy()
Q = np.eye(n)
#in each iteration use A[i][i] to eliminate A[i+1][i]
for i in range(n-1):
    use_val = A_param[i][i]
    to_eli_val = A_param[i+1][i]
    r = math.sqrt(use_val**2 + to_eli_val**2)
    cos = use_val / r 
    sin = to_eli_val / r 
    G = np.eye(n)
    G[i][i] = cos 
    G[i][i+1] = sin 
    G[i+1][i] = -sin 
    G[i+1][i+1] = cos 
    Q = Q @ G.T
    A_param = G @ A_param
    
np.round(A_param,3)
print (np.round(Q@A_param,3))

[[ 4.     3.    -0.    -0.   ]
 [ 3.     3.333 -1.667 -0.   ]
 [-0.    -1.667 -1.32  -0.907]
 [ 0.     0.    -0.907  1.987]]


In [16]:
import numpy as np
import numpy.linalg as la

A = np.array([[1,0,1],[0,1,1],[1,0,1],[0,1,1]])
aplus = la.inv(A.T @A) @A.T

LinAlgError: Singular matrix