In [1]:
def Householder(H, col, row_start, row_end):

    v = np.zeros(row_end-row_start+1)
    v[0] = -np.sign(H[row_start, col])*np.linalg.norm(H[row_start:row_end+1, col])
    v += H[row_start:row_end+1, col]
    return v

In [2]:
import numpy as np 
A = np.array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
n = A.shape[0]
A

array([[ 4,  1, -2,  2],
       [ 1,  2,  0,  1],
       [-2,  0,  3, -2],
       [ 2,  1, -2, -1]])

In [3]:
v = Householder(A, 0, 1, n-1)
v

array([-2., -2.,  2.])

In [4]:
H = np.eye(len(v)) - 2*np.outer(v,v)/np.inner(v,v)

H1 = np.zeros([n,n])
H1[0][0] = 1
H1[1:, 1:] = H
H1

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.33333333, -0.66666667,  0.66666667],
       [ 0.        , -0.66666667,  0.33333333,  0.66666667],
       [ 0.        ,  0.66666667,  0.66666667,  0.33333333]])

In [5]:
A2 = H1@A@H1
np.round(A2,3)

array([[ 4.   ,  3.   , -0.   ,  0.   ],
       [ 3.   ,  3.333, -1.333, -1.   ],
       [-0.   , -1.333, -1.   , -1.333],
       [ 0.   , -1.   , -1.333,  1.667]])

In [42]:
v = Householder(A2, 1, 2, n-1)
v

array([ 0.33333333, -1.        ])

In [44]:
H = np.eye(len(v)) - 2*np.outer(v,v)/np.inner(v,v)
H

array([[ 0.8,  0.6],
       [ 0.6, -0.8]])

In [45]:
H2 = np.zeros([n,n])
H2[0][0] = 1
H2[1][1] = 1
H2[2:, 2:] = H
H2

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.8,  0.6],
       [ 0. ,  0. ,  0.6, -0.8]])

In [48]:
A3 = H2@A2@H2
np.round(A3,3)

array([[ 4.   ,  3.   ,  0.   , -0.   ],
       [ 3.   ,  3.333, -1.667, -0.   ],
       [ 0.   , -1.667, -1.32 , -0.907],
       [-0.   , -0.   , -0.907,  1.987]])

In [59]:
A = np.array([[4,1,-2,2,1],[1,2,0,1,2],[-2,0,3,-2,3],[2,1,-2,-1,4],[1,2,3,4,5]])
n = A.shape[0]
A_param = A.copy()
for i in range(n - 2):
    v = Householder(A_param, i, 1+i, n-1)
    H = np.eye(len(v)) - 2 * np.outer(v,v)/np.inner(v,v)
    Q = np.zeros([n,n])
    for j in range(1+i):
        Q[j][j] = 1
    Q[1+i:, 1+i:] = H 
    A_param = Q@A_param@Q 
np.round(A_param,3)

array([[ 4.   ,  3.162,  0.   , -0.   ,  0.   ],
       [ 3.162,  4.3  ,  1.735,  0.   , -0.   ],
       [ 0.   ,  1.735,  4.753,  5.284,  0.   ],
       [-0.   ,  0.   ,  5.284, -1.009, -1.029],
       [ 0.   , -0.   , -0.   , -1.029,  0.956]])

### Householder full code